### PR TITLE
Fix addNewAsset call + minor improvements

### PR DESCRIPTION
**Pull request by grunichev**
1) Fixed addNewAsset call
2) added requirements.txt for easy dependency installation `pip install -r requirements.txt` 
3) added ibflex parse error message to logs

### CODE REVIEW

**Comment by titov-vv** [comment]
Hi Alexey,
Thanks for fixes in statements import - looks good.
My question is about requirements.txt - I'm not familiar with syntax, but would it be better to have '>=' instead of '==' there?
(and now I have optional ones - zbar and PIL - are there any place for them in requirements.txt?)

**Comment by grunichev** [comment]
@titov-vv regarding `>=` or `==` I would say it depends. If you can trust author or price of broken app due to dependency issue isn't high you can use `>=`  or something like `==0.5.*` if you aren't so brave :)

**Comment by grunichev** [comment]
optional dependencies are usually placed in something like`optional-requirements.txt` as far as I know

**Comment by titov-vv** [comment]
Ok, clear. I'll merge and then change '==' to '>=' - I feel it will be more suitable for those who already have these packages installed for other purposes. And yes, it may break something... but I feel it will be fixed :)

**Pull request merged**
